### ISSUE TITLE
Not able to get markers in my exported image

### ISSUE THREAD

**Issue by Navin-r** [Azure-Samples/azure-maps-image-exporter#1]
I am using this map image exporter for exporting my azure map into the image. In my azure maps, I have added markers. but when I am exporting the image I am able to get the map image but it didn't have the markers. am I missing anything? Can you please help
![azure Map image](https://user-images.githubusercontent.com/62245483/222420899-980d5fa5-69cc-4185-81cd-d07922abd757.png)

**Comment by rbrundritt** [comment]
HtmlMarkers are not supported as those are DOM elements that are not rendered within an HTML canvas.
