### ISSUE TITLE
Npm package support

### ISSUE THREAD

**Issue by Jxlle** [Azure-Samples/azure-maps-image-exporter#2]
### This issue is for a: NPM package support
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

Is it possible to upload this and other azure maps extensions as an npm package for easy distribution? I would think of these extensions as additions to the `azure-maps-control` npm package, such as [turf.js](https://turfjs.org/docs/getting-started) has a hierarchy of packages. It also simplifies the integration process when using Typescript (because no need to augment the original type inside your own project).

**Extra note**: Due to the way our project is structured (we use [Servoy](https://servoy.com/)), it is not possible to extend our `azure-maps-control` type with extension type definitions (such as this one), because they get overwritten by Servoy building its application (so not possible to use the `typeRoots`/`types` etc. `tsConfig.ts` properties). Because we use Typescript, we cannot compile our project while using one of the extensions because the definitions don't exist in the main npm package. Our only **known** solution at the moment is to copy and paste the extension code inside our own component (which pollutes the code). **Is there another way to accomplish this?**

**Comment by rbrundritt** [comment]
Many of the other modules, such as the scale bar and full screen control have been added directly to the main Azure Maps Web SDK and are available in the NPM package (no additional JS or NPM packages required). 

That said, not all modules will be made into NPM packages or added to the main web SDK. Note, all of those are samples, this project included. These were created based on individual requests I came across as a way to show how to create custom modules and add the desired capability. The popularity of each project based on stars/forks/watches is used as an indicator on which capabilities are worth adding to the main web SDK, or making official NPM packages for. This project has 1 star currently, and I think that might be from me. I think this is only the third time I've had anyone mention this project in the dev community.

**Comment by Jxlle** [comment]
@rbrundritt Thanks, totally understand it!

Are you sure that the fullscreen control is in the SDK though? I do not find any references to it inside the typings for the package.

**Comment by rbrundritt** [comment]
I'm not 100% sure if it made it into the NPM package yet. I just noticed some related PR's on the code sample site: 

https://github.com/Azure-Samples/AzureMapsCodeSamples/pull/150

https://github.com/Azure-Samples/AzureMapsCodeSamples/pull/153

**Comment by Jxlle** [comment]
I tested it and it seems that it's not in the latest npm version:

```
// Add style and fullscreen buttons to the top right corner
this.map.controls.add([
    new azmaps.control.StyleControl({ mapStyles: 'all' }),
    // @ts-ignore
    new azmaps.control.FullscreenControl()
], { position: azmaps.ControlPosition.TopRight });
```
        

<img width="487" alt="image" src="https://github.com/user-attachments/assets/3cdb068f-2d94-465a-94df-ff04ba26ccc8">

But I think the rest of my issue was made clear, thanks!
